services:

  db:
    build: 
      context: .
      dockerfile: Dockerfile._db
    ports: 
      - "5434:5434"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    logging:
      options:
        max-size: "100m"
        max-file: "3"
  
    environment:
      - TZ=UTC

    command: -p 5434

  api:
    build: 
      context: .
      dockerfile: Dockerfile.app

    volumes: 
      - ./safarbazi_project:/app
      - ./safarbazi_project/static:/static
      
    command: gunicorn panel.wsgi:application --bind 0.0.0.0:8000
    depends_on:
          - db  
    network_mode: host

    # ports:
      # - "8000:8000"
  nginx:
      build: 
        context: .
        dockerfile: Dockerfile.nginx
      restart: always
      volumes:
        - ./safarbazi_project:/safarbazi_project
        - ./safarbazi_project/static:/static
        - ./default.conf:/etc/nginx/conf.d/default.conf
      # ports:
      #   - 80:80
      network_mode: host
      
      # networks:
      #   - nginx_network
      depends_on:
        - api